-- pgTAP: a comparison names who generated it — a person or the quotation run, exactly one (0067, D-141).
begin;
select plan(3);

insert into work_items (id, organization_id, title, kind, task_status, steps)
values ('f3390000-0000-4000-8000-00000000000a', '10000000-0000-4000-8000-00000000000a', 'pgTAP quotation', 'new_business', 'in_progress', '[]');
insert into opportunities (id, organization_id, client_id, work_item_id, title, class_of_business, created_by)
select 'f3390000-0000-4000-8000-00000000000b', '10000000-0000-4000-8000-00000000000a', c.id, 'f3390000-0000-4000-8000-00000000000a', 'pgTAP', 'Motor', 'a0000000-0000-4000-8000-000000000001'
  from clients c where c.organization_id = '10000000-0000-4000-8000-00000000000a' limit 1;
insert into workflow_runs (id, organization_id, workflow, subject_type, subject_id)
values ('f3390000-0000-4000-8000-00000000000c', '10000000-0000-4000-8000-00000000000a', 'quotation', 'opportunity', 'f3390000-0000-4000-8000-00000000000b');

select lives_ok($$
  insert into quote_comparisons (organization_id, opportunity_id, generated_by_run_id)
  values ('10000000-0000-4000-8000-00000000000a', 'f3390000-0000-4000-8000-00000000000b', 'f3390000-0000-4000-8000-00000000000c')
$$, 'the quotation run may generate a comparison as itself');
select throws_like($$
  insert into quote_comparisons (organization_id, opportunity_id)
  values ('10000000-0000-4000-8000-00000000000a', 'f3390000-0000-4000-8000-00000000000b')
$$, '%quote_comparisons_generated_by_one%', 'a comparison generated by nobody is refused');
select throws_like($$
  insert into quote_comparisons (organization_id, opportunity_id, generated_by, generated_by_run_id)
  values ('10000000-0000-4000-8000-00000000000a', 'f3390000-0000-4000-8000-00000000000b', 'a0000000-0000-4000-8000-000000000001', 'f3390000-0000-4000-8000-00000000000c')
$$, '%quote_comparisons_generated_by_one%', 'a comparison cannot claim both a person and the run');

select * from finish();
rollback;
