import type {
  DemoAutomation,
  DemoClient,
  DemoDocument,
  DemoJob,
  DemoPolicy,
  DemoSearchRecord,
  DemoThread,
  DemoWork,
} from "./contracts.js";

/**
 * The approved fictional brokerage (D-064).
 *
 * Everything a person sees in demo mode comes from here. No component names a client; they take
 * these records through the contracts in `contracts.ts`, which is what makes them components
 * rather than pictures of one brokerage.
 */

export const DEMO_CLIENTS: readonly DemoClient[] = [
  {
    id: "acme",
    name: "Acme Manufacturing Ltd",
    shortName: "Acme Manufacturing",
    initials: "AM",
    sector: "Manufacturing",
    demonstrates: [
      "Active policy intelligence",
      "Coverage checking",
      "Servicing and TOR",
      "Endorsements",
      "Claims",
      "Premium reconciliation",
      "Document comparison",
      "Communication",
      "Policy history",
    ],
  },
  {
    id: "karibu",
    name: "Karibu Logistics Ltd",
    shortName: "Karibu Logistics",
    initials: "KL",
    sector: "Transport and logistics",
    demonstrates: [
      "Opportunity detection",
      "Quote readiness",
      "Insurer selection",
      "Quotation comparison",
      "Client recommendation",
      "Placement and underwriting requirements",
    ],
  },
  {
    id: "bluewave",
    name: "Bluewave Properties Ltd",
    shortName: "Bluewave Properties",
    initials: "BP",
    sector: "Property",
    demonstrates: [
      "Renewal risk",
      "Missing renewal information",
      "Term tracking",
      "Premium-change explanation",
      "Document conflict",
    ],
  },
  {
    id: "greencare",
    name: "GreenCare Clinics Ltd",
    shortName: "GreenCare Clinics",
    initials: "GC",
    sector: "Healthcare",
    demonstrates: [
      "Claim creation from email",
      "Policy and equipment matching",
      "Missing claim documents",
      "Settlement offer, acceptance and payment kept separate",
    ],
  },
  {
    id: "mara",
    name: "Mara Foods Exporters Ltd",
    shortName: "Mara Foods",
    initials: "MF",
    sector: "Food export",
    demonstrates: [
      "Client balance",
      "Overdue premium",
      "Unmatched receipts",
      "Payment matching",
      "Evidence-backed money calculations",
    ],
  },
  {
    id: "northstar",
    name: "Northstar Traders Ltd",
    shortName: "Northstar Traders",
    initials: "NT",
    sector: "Trading",
    demonstrates: [
      "Cancellation and economic closure",
      "Return premium",
      "Certificate recovery",
      "Commission adjustment",
    ],
  },
];

export function demoClient(id: string | null): DemoClient | undefined {
  return id ? DEMO_CLIENTS.find((c) => c.id === id) : undefined;
}

export const DEMO_POLICIES: readonly DemoPolicy[] = [
  {
    id: "acme-motor",
    clientId: "acme",
    name: "Commercial Motor Fleet",
    policyNumber: "ASAP-MTR-2026-00418",
    insurer: "Meridian General Insurance",
    periodStart: "1 Jan 2026",
    periodEnd: "31 Dec 2026",
    status: "Active",
    facts: [
      ["Vehicles", "42"],
      ["Original premium", "KES 8,420,000"],
      ["Endorsed premium", "KES 8,634,200"],
      ["Cover", "Comprehensive"],
    ],
  },
  {
    id: "bluewave-property",
    clientId: "bluewave",
    name: "Property Owners Combined",
    policyNumber: "ASAP-PRP-2025-00231",
    insurer: "Jubilee Allianz",
    periodStart: "15 Oct 2025",
    periodEnd: "14 Oct 2026",
    status: "Renewal due",
    facts: [
      ["Renewal date", "14 October 2026"],
      ["Sum insured", "KES 462,000,000"],
      ["Terms received", "Not usable"],
    ],
  },
  {
    id: "greencare-machinery",
    clientId: "greencare",
    name: "Machinery Breakdown",
    policyNumber: "ASAP-MBD-2026-00107",
    insurer: "Old Mutual General",
    periodStart: "1 Mar 2026",
    periodEnd: "28 Feb 2027",
    status: "Active",
    facts: [
      ["Open claim", "CLM-114"],
      ["Settlement", "Offered and accepted"],
      ["Money received", "Not yet"],
    ],
  },
  {
    id: "mara-marine",
    clientId: "mara",
    name: "Marine Cargo",
    policyNumber: "ASAP-MAR-2026-00090",
    insurer: "APA Insurance",
    periodStart: "1 Feb 2026",
    periodEnd: "31 Jan 2027",
    status: "Active",
    facts: [
      ["Outstanding", "KES 1,284,000"],
      ["Oldest item", "62 days"],
    ],
  },
  {
    id: "northstar-git",
    clientId: "northstar",
    name: "Goods in Transit",
    policyNumber: "ASAP-GIT-2026-00055",
    insurer: "CIC General",
    periodStart: "1 Apr 2026",
    periodEnd: "31 Mar 2027",
    status: "Cancellation requested",
    facts: [
      ["Requested", "Cancellation"],
      ["Insurer confirmation", "Not received"],
    ],
  },
];

/** The eight approved Work items. Each opens a scenario, so nothing is a dead row. */
export const DEMO_WORK: readonly DemoWork[] = [
  {
    id: "w-acme-kdn",
    title: "Add KDN 482Q to Acme's cover",
    clientId: "acme",
    state: "waiting",
    reason: "Meridian has not confirmed cover for the vehicle. A client request is not proof of cover.",
    scenarioId: "coverage-check",
    owner: "Grace Wanjiku",
    updatedAt: "2026-09-10T09:20:00Z",
    workType: "Servicing / TOR",
    pill: "High",
    headline: "Add KDN 482Q to cover",
    summary: "Insurer confirmation missing",
    contextLabel: "Acme Manufacturing · Commercial Motor Fleet",
    jobIds: ["j-meridian-confirm"],
    history: [
      ["10 Sep", "Client requested same-day cover for KDN 482Q"],
      ["10 Sep", "ASAP checked the latest schedule, certificate register and insurer correspondence"],
      ["10 Sep", "Insurer request prepared for a person to send"],
    ],
  },
  {
    id: "w-jane-claim",
    title: "Investigate Jane's delayed claim",
    clientId: "acme",
    state: "active",
    reason: "Claim CLM-082 has not moved for five days. No assessor has been allocated.",
    scenarioId: "claim-investigation",
    owner: "James Mwangi",
    updatedAt: "2026-09-09T14:05:00Z",
    workType: "Claim investigation",
    pill: "Waiting",
    headline: "Jane’s claim · CLM-082",
    summary: "Assessor not allocated",
    contextLabel: "Acme Manufacturing · Commercial Motor Fleet",
    jobIds: [],
    history: [["5 Sep", "Claim registered with Meridian"], ["9 Sep", "ASAP noticed no movement for five days"]],
  },
  {
    id: "w-karibu-quotes",
    title: "Compare Karibu's fleet quotations",
    clientId: "karibu",
    state: "review",
    reason: "Three quotations are in and compared. A person chooses what to recommend.",
    scenarioId: "compare-quotations",
    owner: "Grace Wanjiku",
    updatedAt: "2026-09-10T11:00:00Z",
    workType: "Quote comparison",
    pill: "For review",
    headline: "Karibu fleet quotations",
    summary: "Three usable options ready",
    contextLabel: "Karibu Logistics · New business",
    jobIds: ["j-compare-schedules"],
    history: [["8 Sep", "Terms requested from three insurers"], ["10 Sep", "Comparison prepared"]],
  },
  {
    id: "w-karibu-placement",
    title: "Resolve Karibu's placement requirements",
    clientId: "karibu",
    state: "active",
    reason: "The insurer's underwriting requirements are not all satisfied.",
    scenarioId: "placement-blocker",
    owner: "Amina Kamau",
    updatedAt: "2026-09-10T08:30:00Z",
    workType: "Placement",
    pill: "Waiting",
    headline: "Karibu placement requirements",
    summary: "Two underwriting blockers",
    contextLabel: "Karibu Logistics · APA",
    jobIds: [],
    history: [["9 Sep", "Underwriting requirements received"]],
  },
  {
    id: "w-bluewave-renewal",
    title: "Progress Bluewave's renewal",
    clientId: "bluewave",
    state: "waiting",
    reason: "Renewal terms were received but are not usable. Jubilee Allianz has been asked again.",
    scenarioId: "renewal-risk",
    owner: "Grace Wanjiku",
    updatedAt: "2026-09-08T16:40:00Z",
    workType: "Renewal",
    pill: "High",
    headline: "Bluewave property renewal",
    summary: "34 days · no usable terms",
    contextLabel: "Bluewave Properties · Property",
    jobIds: ["j-bluewave-info"],
    history: [["1 Sep", "Renewal approached"], ["8 Sep", "Terms received without the schedule"]],
  },
  {
    id: "w-greencare-claim",
    title: "Prepare GreenCare's claim notification",
    clientId: "greencare",
    state: "review",
    reason: "A claim notification is drafted from the client's email. Nothing has been sent.",
    scenarioId: "property-claim",
    owner: "James Mwangi",
    updatedAt: "2026-09-10T10:10:00Z",
    workType: "Claim",
    pill: "Active",
    headline: "GreenCare equipment damage",
    summary: "Draft notification prepared",
    contextLabel: "GreenCare Clinics · Machinery",
    jobIds: ["j-client-comms"],
    history: [["10 Sep", "Accident email received"], ["10 Sep", "Claim notification prepared"]],
  },
  {
    id: "w-mara-balance",
    title: "Reconcile Mara Foods' balance",
    clientId: "mara",
    state: "active",
    reason: "Premium is overdue and two receipts are unmatched.",
    scenarioId: "client-balance",
    owner: "Amina Kamau",
    updatedAt: "2026-09-09T09:00:00Z",
    workType: "Money",
    pill: "Waiting",
    headline: "Mara Foods balance",
    summary: "KES 860K overdue",
    contextLabel: "Mara Foods · Two policies",
    jobIds: [],
    history: [["1 Sep", "Statement received"], ["9 Sep", "Two receipts could not be matched"]],
  },
  {
    id: "w-acme-update",
    title: "Review Acme's client update",
    clientId: "acme",
    state: "review",
    reason: "A client update is drafted from the open work. Nothing has been sent: a person reads it and decides.",
    scenarioId: "client-update",
    owner: "Grace Wanjiku",
    updatedAt: "2026-09-07T15:00:00Z",
    workType: "Communication",
    pill: "For review",
    headline: "Update Acme on outstanding work",
    summary: "Draft ready · not sent",
    contextLabel: "Acme Manufacturing · Motor",
    jobIds: [],
    history: [
      ["7 Sep", "Update drafted from the open work on this policy"],
      ["7 Sep", "Waiting for a person to review it"],
    ],
  },
];

/**
 * What ASAP is processing. Outcome language is deliberate: "comparison prepared", never
 * "policy renewed". A finished Job is an output, not a business outcome.
 */
export const DEMO_JOBS: readonly DemoJob[] = [
  {
    id: "j-compare-schedules",
    title: "Comparing policy schedules",
    clientId: "karibu",
    state: "running",
    outcome: "Comparing three quotations line by line",
    startedAt: "2026-09-10T10:55:00Z",
    steps: [
      { label: "Read the three quotation documents", state: "done" },
      { label: "Align cover, exclusions and excesses", state: "now" },
      { label: "Prepare the comparison", state: "todo" },
    ],
    workId: "w-karibu-quotes",
  },
  {
    id: "j-meridian-confirm",
    title: "Waiting for Meridian cover confirmation",
    clientId: "acme",
    state: "waiting",
    outcome: "Request sent. Waiting on the insurer, not on ASAP.",
    startedAt: "2026-09-10T09:25:00Z",
    steps: [
      { label: "Prepare the insurer request", state: "done" },
      { label: "A person sent it", state: "done" },
      { label: "Meridian confirms cover", state: "now" },
    ],
    workId: "w-acme-kdn",
  },
  {
    id: "j-bluewave-info",
    title: "Waiting for Bluewave renewal information",
    clientId: "bluewave",
    state: "waiting",
    outcome: "Chased. The schedule has not arrived.",
    startedAt: "2026-09-08T16:45:00Z",
    steps: [
      { label: "Read the terms received", state: "done" },
      { label: "Identify what is missing", state: "done" },
      { label: "Jubilee Allianz sends the schedule", state: "now" },
    ],
    workId: "w-bluewave-renewal",
  },
  {
    id: "j-client-comms",
    title: "Prepared client communication requiring review",
    clientId: "greencare",
    state: "needs_human",
    outcome: "A claim notification is drafted. Sending is a person's decision.",
    startedAt: "2026-09-10T10:05:00Z",
    steps: [
      { label: "Read the client's accident email", state: "done" },
      { label: "Match the policy and the equipment", state: "done" },
      { label: "Draft the notification", state: "done" },
      { label: "A person reviews and sends", state: "now" },
    ],
    workId: "w-greencare-claim",
  },
  {
    id: "j-extraction",
    title: "Reading Bluewave's renewal quote",
    clientId: "bluewave",
    state: "failed",
    outcome: "Could not finish: two pages would not extract. Nothing was recorded from them.",
    startedAt: "2026-09-08T16:20:00Z",
    steps: [
      { label: "Open the document", state: "done" },
      { label: "Extract pages 1–4", state: "done" },
      { label: "Extract pages 5–6", state: "failed" },
    ],
    workId: "w-bluewave-renewal",
  },
  {
    id: "j-acme-compare",
    title: "Compared the original and latest schedules",
    clientId: "acme",
    state: "completed",
    outcome: "Comparison prepared. The premium variance is explained by two endorsements.",
    startedAt: "2026-09-07T09:00:00Z",
    steps: [
      { label: "Read both schedules", state: "done" },
      { label: "Align every field", state: "done" },
      { label: "Prepare the comparison", state: "done" },
    ],
    workId: null,
  },
];

export const DEMO_AUTOMATIONS: readonly DemoAutomation[] = [
  {
    id: "a-servicing",
    name: "Detect new servicing requests",
    enabled: true,
    trigger: "A client email arrives",
    conditions: ["It names a vehicle, an address or an item", "The client has an active policy"],
    skills: ["email.classify", "policy.match", "servicing.prepare"],
    preparedAction: "Open servicing Work with the request and the matching policy",
    approval: "A person approves before anything reaches the insurer",
    exceptionHandling: "If no policy matches, raise it for a person rather than guessing",
    lastTest: "Passed on 9 September — matched 7 of 7 sample emails",
    runs: [
      { at: "10 Sep 09:14", outcome: "Prepared", detail: "Acme — KDN 482Q servicing request" },
      { at: "8 Sep 11:02", outcome: "Did nothing", detail: "No active policy matched the address" },
    ],
  },
  {
    id: "a-stalled-claims",
    name: "Monitor claims that have stopped moving",
    enabled: true,
    trigger: "A claim has no recorded movement for five days",
    conditions: ["The claim is open", "The last event is older than five days"],
    skills: ["claim.track", "insurer.followup"],
    preparedAction: "Open an investigation and draft a chase to the insurer",
    approval: "A person approves the chase",
    exceptionHandling: "If the insurer replied but was not recorded, ask a person to record it",
    lastTest: "Passed on 9 September",
    runs: [{ at: "9 Sep 07:00", outcome: "Prepared", detail: "Acme — CLM-082 has not moved for 5 days" }],
  },
  {
    id: "a-statement-variance",
    name: "Check insurer statements for premium variances",
    enabled: true,
    trigger: "An insurer statement is received",
    conditions: ["The statement covers a period we hold policies for"],
    skills: ["money.reconcile", "document.extract"],
    preparedAction: "Prepare a reconciliation showing each line that does not agree",
    approval: "A person approves any adjustment",
    exceptionHandling: "An unreadable statement becomes a task, not a silent skip",
    lastTest: "Passed on 7 September — explained a KES 214,200 variance",
    runs: [{ at: "7 Sep 16:20", outcome: "Prepared", detail: "Meridian — variance explained by two endorsements" }],
  },
  {
    id: "a-accident-email",
    name: "Detect an accident email and prepare Claim Work",
    enabled: false,
    trigger: "A client email describes an incident",
    conditions: ["The client has a policy covering the item", "The incident date is within the period"],
    skills: ["email.classify", "policy.match", "claim.prepare"],
    preparedAction: "Open claim Work and draft the notification",
    approval: "A person reviews and sends the notification",
    exceptionHandling: "If the period does not cover the date, say so rather than registering a claim",
    lastTest: "Not tested since the last change",
    runs: [],
  },
  {
    id: "a-renewal",
    name: "Prepare a renewal before expiry",
    enabled: true,
    trigger: "A policy period is 60 days from its end",
    conditions: ["The policy is active", "No renewal Work is already open"],
    skills: ["renewal.prepare", "document.check_missing"],
    preparedAction: "Open renewal Work and list what is missing",
    approval: "A person approves the approach to market",
    exceptionHandling: "If the client has asked to cancel, do not prepare a renewal",
    lastTest: "Passed on 1 September",
    runs: [{ at: "1 Sep 06:00", outcome: "Prepared", detail: "Bluewave — renewal opened 43 days out" }],
  },
  {
    id: "a-insurer-terms",
    name: "React to incoming insurer terms",
    enabled: true,
    trigger: "An insurer sends terms",
    conditions: ["There is open Work awaiting terms from that insurer"],
    skills: ["quote.extract", "quote.check_comparability"],
    preparedAction: "Record the terms against the Work and flag anything not comparable",
    approval: "A person approves before terms reach the client",
    exceptionHandling: "Terms missing exclusions or excesses are marked not comparable",
    lastTest: "Passed on 10 September",
    runs: [{ at: "10 Sep 10:50", outcome: "Prepared", detail: "Karibu — three sets of terms recorded" }],
  },
];

export const DEMO_THREADS: readonly DemoThread[] = [
  {
    id: "t-meridian-kdn",
    subject: "Urgent TOR — Acme Manufacturing Ltd — KDN 482Q",
    clientId: "acme",
    counterparty: "motor.underwriting@meridiangeneral.co.ke",
    messages: [
      {
        id: "m1",
        from: "peter.kariuki@acmemanufacturing.co.ke",
        to: "grace@asapbrokers.co.ke",
        at: "10 Sep 08:12",
        direction: "inbound",
        body: "Grace, we have taken delivery of KDN 482Q this morning. Please put it on cover today.",
      },
    ],
  },
  {
    id: "t-greencare-incident",
    subject: "Equipment failure at the Karen clinic",
    clientId: "greencare",
    counterparty: "admin@greencareclinics.co.ke",
    messages: [
      {
        id: "m1",
        from: "admin@greencareclinics.co.ke",
        to: "james@asapbrokers.co.ke",
        at: "10 Sep 07:40",
        direction: "inbound",
        body: "Our steriliser failed overnight and cannot be repaired on site. What do we need to do?",
      },
    ],
  },
  {
    id: "t-bluewave-terms",
    subject: "Renewal terms — Bluewave Properties",
    clientId: "bluewave",
    counterparty: "renewals@jubileeallianz.co.ke",
    messages: [
      {
        id: "m1",
        from: "renewals@jubileeallianz.co.ke",
        to: "grace@asapbrokers.co.ke",
        at: "8 Sep 16:02",
        direction: "inbound",
        body: "Terms attached for the 2026 renewal. Schedule to follow.",
      },
      {
        id: "m2",
        from: "grace@asapbrokers.co.ke",
        to: "renewals@jubileeallianz.co.ke",
        at: "8 Sep 16:48",
        direction: "outbound",
        body: "Thank you. We cannot compare without the schedule — could you send it today?",
      },
    ],
  },
];

export const DEMO_DOCUMENTS: readonly DemoDocument[] = [
  {
    id: "d-acme-schedule",
    clientId: "acme",
    name: "Acme motor schedule — Endorsement 04",
    kind: "Policy schedule",
    pages: 6,
    highlight: { field: "Vehicles listed", value: "42", page: 2, state: "known" },
  },
  {
    id: "d-acme-cert",
    clientId: "acme",
    name: "Certificate register extract",
    kind: "Certificate register",
    pages: 1,
    highlight: { field: "KDN 482Q", value: "No certificate issued", page: 1, state: "missing" },
  },
  {
    id: "d-bluewave-quote",
    clientId: "bluewave",
    name: "Bluewave renewal quote v2",
    kind: "Quotation",
    pages: 6,
    highlight: { field: "Sum insured", value: "KES 438,000,000", page: 3, state: "conflicting" },
  },
  {
    id: "d-bluewave-schedule",
    clientId: "bluewave",
    name: "Bluewave schedule v3",
    kind: "Policy schedule",
    pages: 8,
    highlight: { field: "Sum insured", value: "KES 462,000,000", page: 4, state: "known" },
  },
];

/** Everything Search can find. Each row opens a real context. */
export const DEMO_SEARCH: readonly DemoSearchRecord[] = [
  ...DEMO_CLIENTS.map((c) => ({
    id: `client-${c.id}`,
    kind: "client" as const,
    title: c.name,
    subtitle: c.sector,
    to: `/demo/client/${c.id}`,
  })),
  ...DEMO_POLICIES.map((p) => ({
    id: `policy-${p.id}`,
    kind: "policy" as const,
    title: p.name,
    subtitle: `${p.policyNumber} · ${p.insurer}`,
    to: `/demo/client/${p.clientId}`,
  })),
  {
    id: "claim-082",
    kind: "claim",
    title: "CLM-082 — Jane Wanjiku, motor",
    subtitle: "Acme Manufacturing · waiting for assessor allocation",
    to: "/ask?scenario=claim-investigation",
  },
  {
    id: "claim-114",
    kind: "claim",
    title: "CLM-114 — sterilis­er breakdown",
    subtitle: "GreenCare Clinics · settlement accepted, not paid",
    to: "/ask?scenario=settlement-status",
  },
  ...DEMO_WORK.map((w) => ({
    id: `work-${w.id}`,
    kind: "work" as const,
    title: w.title,
    subtitle: w.reason,
    to: `/work/${w.id}`,
  })),
  ...DEMO_JOBS.map((j) => ({
    id: `job-${j.id}`,
    kind: "job" as const,
    title: j.title,
    subtitle: j.outcome,
    to: `/jobs/${j.id}`,
  })),
  ...DEMO_DOCUMENTS.map((d) => ({
    id: `doc-${d.id}`,
    kind: "document" as const,
    title: d.name,
    subtitle: `${d.kind} · ${d.pages} pages`,
    to: `/documents/${d.id}`,
  })),
  ...DEMO_THREADS.map((t) => ({
    id: `email-${t.id}`,
    kind: "email" as const,
    title: t.subject,
    subtitle: t.counterparty,
    to: `/email/${t.id}`,
  })),
  {
    id: "analysis-insurer",
    kind: "analysis",
    title: "Insurer response performance",
    subtitle: "How quickly each insurer answers, across the book",
    to: "/ask?scenario=insurer-performance-report",
  },
  {
    id: "analysis-commission",
    kind: "analysis",
    title: "Commission outstanding by insurer",
    subtitle: "What is owed to the brokerage and how old it is",
    to: "/ask?scenario=commission-outstanding",
  },
];

/** The three people a demo Work item can be assigned to. */
export const DEMO_TEAM = ["Grace Wanjiku", "James Mwangi", "Amina Kamau"] as const;
