import { z } from "zod";
import { emailSchema, uuidSchema } from "./common.js";

export const invitationStatusSchema = z.enum(["pending", "accepted", "revoked", "expired"]);
export type InvitationStatus = z.infer<typeof invitationStatusSchema>;

/** POST /organizations/current/invitations — §7 Step 2 */
export const createInvitationRequestSchema = z.object({
  email: emailSchema,
  role_id: uuidSchema,
});
export type CreateInvitationRequest = z.infer<typeof createInvitationRequestSchema>;

export const createInvitationResponseSchema = z.object({
  invitation_id: uuidSchema,
  email: z.string(),
  expires_at: z.string(),
  /** Only present when APP_ENV is local, where no email is sent. Never in staging or production. */
  accept_url: z.string().url().optional(),
});
export type CreateInvitationResponse = z.infer<typeof createInvitationResponseSchema>;

export const invitationSummarySchema = z.object({
  id: uuidSchema,
  email: z.string(),
  role: z.object({ id: uuidSchema, key: z.string(), name: z.string() }),
  status: invitationStatusSchema,
  invited_by: z
    .object({ id: uuidSchema, email: z.string(), full_name: z.string().nullable() })
    .nullable(),
  expires_at: z.string(),
  created_at: z.string(),
});
export type InvitationSummary = z.infer<typeof invitationSummarySchema>;
export const invitationsResponseSchema = z.object({
  invitations: z.array(invitationSummarySchema),
});
export type InvitationsResponse = z.infer<typeof invitationsResponseSchema>;

/** GET /invitations/:token — shown before sign-in */
export const invitationPreviewSchema = z.object({
  organization_name: z.string(),
  role_name: z.string(),
  email: z.string(),
  status: invitationStatusSchema,
  expires_at: z.string(),
});
export type InvitationPreview = z.infer<typeof invitationPreviewSchema>;

/** POST /invitations/:token/accept */
export const acceptInvitationResponseSchema = z.object({ organization_id: uuidSchema });
export type AcceptInvitationResponse = z.infer<typeof acceptInvitationResponseSchema>;

/** The raw token: 32 random bytes, base64url, generated by the API. Only its SHA-256 is stored. */
export const invitationTokenSchema = z.string().regex(/^[A-Za-z0-9_-]{43}$/);
