-- 0045 — Connecting a mailbox, and reading it under control.
--
-- 0035 gave a mailbox somewhere to keep its encrypted tokens and its provider cursor. What it did
-- not give was the two things that make connecting and reading safe rather than merely possible:
--
--  - **An authorisation round trip that cannot be forged.** The `state` parameter is generated by
--    the server, stored here as a digest, single-use and short-lived. A callback presenting a
--    state that was never issued, has expired, or has already been used is refused — and refused
--    by a row, not by a variable in a process that may have restarted since.
--  - **A sync that is a fact rather than a word.** Every pass is a row: when it started, what it
--    read, what it saved, where the checkpoint was before and after, and why it stopped if it
--    stopped badly. "Syncing" is then something the server can prove, and a failure can say what
--    was already saved and which checkpoint is safe to resume from.
--
-- A sync that fails half way is not rolled back. Messages already saved are the brokerage's own
-- correspondence and deleting them because a later page failed would lose real work; the run says
-- what it managed and the checkpoint stays where it was safely written.

create table mailbox_oauth_states (
  id               uuid primary key default gen_random_uuid(),
  organization_id  uuid not null references organizations(id) on delete cascade,
  provider         text not null check (provider in ('gmail','microsoft')),
  -- The digest of the state parameter, never the value: a database reader cannot mint a callback.
  state_hash       text not null unique,
  requested_by     uuid not null references users(id),
  -- Single-use. Set the moment a callback is accepted, so a replayed callback finds it spent.
  consumed_at      timestamptz,
  expires_at       timestamptz not null,
  created_at       timestamptz not null default now()
);
create index mailbox_oauth_states_organization_id_idx on mailbox_oauth_states (organization_id);
create index mailbox_oauth_states_requested_by_idx on mailbox_oauth_states (requested_by);
create index mailbox_oauth_states_expires_at_idx on mailbox_oauth_states (expires_at);

comment on table mailbox_oauth_states is
  'Single-use, short-lived authorisation states. Stored as digests; the value lives only in the redirect.';

-- One pass of reading a mailbox. This is what makes "Syncing" true.
create table mailbox_sync_runs (
  id               uuid primary key default gen_random_uuid(),
  organization_id  uuid not null references organizations(id) on delete cascade,
  mailbox_id       uuid not null references mailboxes(id) on delete cascade,
  state            text not null default 'running'
    check (state in ('running','succeeded','failed')),
  trigger          text not null check (trigger in ('first_connection','person','schedule')),
  started_at       timestamptz not null default now(),
  finished_at      timestamptz,
  -- What it actually did. Counted as it goes, so a failed run still reports what it saved.
  threads_seen     integer not null default 0 check (threads_seen >= 0),
  messages_saved   integer not null default 0 check (messages_saved >= 0),
  attachments_saved integer not null default 0 check (attachments_saved >= 0),
  -- Where the checkpoint was before this run, and where it ended up. A failed run keeps `after`
  -- null, which is what tells a person the resume point is still the one before.
  cursor_before    text,
  cursor_after     text,
  -- Plain language. Never a provider body, which can echo the brokerage's own correspondence.
  error            text,
  -- True when the provider's checkpoint was too old to use and a bounded re-read was needed.
  checkpoint_expired boolean not null default false,
  constraint mailbox_sync_runs_failure_has_a_reason check (state <> 'failed' or error is not null),
  constraint mailbox_sync_runs_finished_states_have_a_time check (
    state = 'running' or finished_at is not null)
);
create index mailbox_sync_runs_organization_id_started_at_idx
  on mailbox_sync_runs (organization_id, started_at desc);
create index mailbox_sync_runs_mailbox_id_started_at_idx
  on mailbox_sync_runs (mailbox_id, started_at desc);
-- One pass at a time per mailbox. A second request while one is running finds this and joins it
-- rather than reading the same messages twice.
create unique index mailbox_sync_runs_one_running_per_mailbox
  on mailbox_sync_runs (mailbox_id) where state = 'running';

comment on table mailbox_sync_runs is
  'One pass of reading a mailbox. A failed run keeps what it saved; only cursor_after is withheld.';

-- When the checkpoint was last written, so a stale worker cannot move it backwards.
alter table mailboxes add column sync_cursor_updated_at timestamptz;
comment on column mailboxes.sync_cursor_updated_at is
  'Guards the checkpoint: a run that started before this wrote cannot overwrite a newer cursor.';

alter table mailbox_oauth_states enable row level security;
alter table mailbox_sync_runs enable row level security;

/*
 * The authorisation state is deliberately not readable by anybody through RLS. It is written and
 * consumed by the API with the service connection, during a redirect that has no session at all —
 * the state *is* the authentication. Enabling row level security with no policy is the way to say
 * "no tenant path reaches this", and it is what stops a signed-in person listing or guessing
 * another brokerage's pending authorisations.
 */

create policy tenant_select on mailbox_sync_runs for select to authenticated, asap_worker
  using (app.can_access(organization_id));
create policy tenant_insert on mailbox_sync_runs for insert to authenticated, asap_worker
  with check (app.can_access(organization_id));
create policy tenant_update on mailbox_sync_runs for update to authenticated, asap_worker
  using (app.can_access(organization_id)) with check (app.can_access(organization_id));

grant select, insert, update on mailbox_sync_runs to authenticated, asap_worker;
